INSERT INTO ingredientes (nombre) VALUES ('Zanahoria');
INSERT INTO ingredientes (nombre) VALUES ('Brócoli');
INSERT INTO ingredientes (nombre) VALUES ('Espinacas');
INSERT INTO ingredientes (nombre) VALUES ('Coliflor');
INSERT INTO ingredientes (nombre) VALUES ('Pimiento rojo');
INSERT INTO ingredientes (nombre) VALUES ('Calabaza');
INSERT INTO ingredientes (nombre) VALUES ('Cebolla');
INSERT INTO ingredientes (nombre) VALUES ('Acelga');
INSERT INTO ingredientes (nombre) VALUES ('Papa');
INSERT INTO ingredientes (nombre) VALUES ('Camote');
INSERT INTO ingredientes (nombre) VALUES ('Lechuga');
INSERT INTO ingredientes (nombre) VALUES ('Repollo');
INSERT INTO ingredientes (nombre) VALUES ('Pepino');
INSERT INTO ingredientes (nombre) VALUES ('Apio');
INSERT INTO ingredientes (nombre) VALUES ('Tomate');
INSERT INTO ingredientes (nombre) VALUES ('Champiñón');
INSERT INTO ingredientes (nombre) VALUES ('Alcachofa');
INSERT INTO ingredientes (nombre) VALUES ('Cebollino');
INSERT INTO ingredientes (nombre) VALUES ('Rábano');
INSERT INTO ingredientes (nombre) VALUES ('Berenjena');
INSERT INTO ingredientes (nombre) VALUES ('Espárragos');
INSERT INTO ingredientes (nombre) VALUES ('Remolacha');
INSERT INTO ingredientes (nombre) VALUES ('Maíz');
INSERT INTO ingredientes (nombre) VALUES ('Guisantes');
INSERT INTO ingredientes (nombre) VALUES ('Calabacín');
INSERT INTO ingredientes (nombre) VALUES ('Chile');
INSERT INTO ingredientes (nombre) VALUES ('Ajo');
INSERT INTO ingredientes (nombre) VALUES ('Jengibre');
INSERT INTO ingredientes (nombre) VALUES ('Hinojo');
INSERT INTO ingredientes (nombre) VALUES ('Berro');
INSERT INTO ingredientes (nombre) VALUES ('Endibia');
INSERT INTO ingredientes (nombre) VALUES ('Acelga suiza');
INSERT INTO ingredientes (nombre) VALUES ('Col rizada');
INSERT INTO ingredientes (nombre) VALUES ('Rúcula');
INSERT INTO ingredientes (nombre) VALUES ('Escarola');
INSERT INTO ingredientes (nombre) VALUES ('Perejil');
INSERT INTO ingredientes (nombre) VALUES ('Cilantro');
INSERT INTO ingredientes (nombre) VALUES ('Eneldo');
INSERT INTO ingredientes (nombre) VALUES ('Albahaca');
INSERT INTO ingredientes (nombre) VALUES ('Orégano');
INSERT INTO ingredientes (nombre) VALUES ('Romero');
INSERT INTO ingredientes (nombre) VALUES ('Salvia');
INSERT INTO ingredientes (nombre) VALUES ('Menta');
INSERT INTO ingredientes (nombre) VALUES ('Hierbabuena');
INSERT INTO ingredientes (nombre) VALUES ('Tomillo');
INSERT INTO ingredientes (nombre) VALUES ('Puerro');
INSERT INTO ingredientes (nombre) VALUES ('Hojas de parra');
INSERT INTO ingredientes (nombre) VALUES ('Col');
INSERT INTO ingredientes (nombre) VALUES ('Col de Bruselas');
INSERT INTO ingredientes (nombre) VALUES ('Nabo');
INSERT INTO ingredientes (nombre) VALUES ('Colinabo');
INSERT INTO ingredientes (nombre) VALUES ('Rábano picante');
INSERT INTO ingredientes (nombre) VALUES ('Bambú');
INSERT INTO ingredientes (nombre) VALUES ('Setas');
INSERT INTO ingredientes (nombre) VALUES ('Ñame');
INSERT INTO ingredientes (nombre) VALUES ('Manzana');
INSERT INTO ingredientes (nombre) VALUES ('Plátano');
INSERT INTO ingredientes (nombre) VALUES ('Naranja');
INSERT INTO ingredientes (nombre) VALUES ('Uva');
INSERT INTO ingredientes (nombre) VALUES ('Pera');
INSERT INTO ingredientes (nombre) VALUES ('Kiwi');
INSERT INTO ingredientes (nombre) VALUES ('Fresas');
INSERT INTO ingredientes (nombre) VALUES ('Piña');
INSERT INTO ingredientes (nombre) VALUES ('Mango');
INSERT INTO ingredientes (nombre) VALUES ('Sandía');
INSERT INTO ingredientes (nombre) VALUES ('Melón');
INSERT INTO ingredientes (nombre) VALUES ('Cereza');
INSERT INTO ingredientes (nombre) VALUES ('Limón');
INSERT INTO ingredientes (nombre) VALUES ('Limón verde');
INSERT INTO ingredientes (nombre) VALUES ('Mandarina');
INSERT INTO ingredientes (nombre) VALUES ('Ciruela');
INSERT INTO ingredientes (nombre) VALUES ('Melocotón');
INSERT INTO ingredientes (nombre) VALUES ('Albaricoque');
INSERT INTO ingredientes (nombre) VALUES ('Higo');
INSERT INTO ingredientes (nombre) VALUES ('Granada');
INSERT INTO ingredientes (nombre) VALUES ('Lima');
INSERT INTO ingredientes (nombre) VALUES ('Aguacate');
INSERT INTO ingredientes (nombre) VALUES ('Guayaba');
INSERT INTO ingredientes (nombre) VALUES ('Maracuyá');
INSERT INTO ingredientes (nombre) VALUES ('Papaya');
INSERT INTO ingredientes (nombre) VALUES ('Coco');
INSERT INTO ingredientes (nombre) VALUES ('Grosella');
INSERT INTO ingredientes (nombre) VALUES ('Fruta de la pasión');
INSERT INTO ingredientes (nombre) VALUES ('Arándano');
INSERT INTO ingredientes (nombre) VALUES ('Fruta del dragón');
INSERT INTO ingredientes (nombre) VALUES ('Lichi');
INSERT INTO ingredientes (nombre) VALUES ('Litchi');
INSERT INTO ingredientes (nombre) VALUES ('Pitahaya');
INSERT INTO ingredientes (nombre) VALUES ('Kumquat');
INSERT INTO ingredientes (nombre) VALUES ('Mangostino');
INSERT INTO ingredientes (nombre) VALUES ('Morera');
INSERT INTO ingredientes (nombre) VALUES ('Higo chumbo');
INSERT INTO ingredientes (nombre) VALUES ('Chirimoya');
INSERT INTO ingredientes (nombre) VALUES ('Mandacarú');
INSERT INTO ingredientes (nombre) VALUES ('Naranjilla');
INSERT INTO ingredientes (nombre) VALUES ('Pepino dulce');
INSERT INTO ingredientes (nombre) VALUES ('Zapote negro');
INSERT INTO ingredientes (nombre) VALUES ('Uchuva');
INSERT INTO ingredientes (nombre) VALUES ('Mora');
INSERT INTO ingredientes (nombre) VALUES ('Zarzamora');
INSERT INTO ingredientes (nombre) VALUES ('Guanábana');
INSERT INTO ingredientes (nombre) VALUES ('Breva');
INSERT INTO ingredientes (nombre) VALUES ('Anona');
INSERT INTO ingredientes (nombre) VALUES ('Pomelo');
INSERT INTO ingredientes (nombre) VALUES ('Tamarindo');
INSERT INTO ingredientes (nombre) VALUES ('Caqui');
INSERT INTO ingredientes (nombre) VALUES ('Pepino amargo');
INSERT INTO ingredientes (nombre) VALUES ('Níspero');
INSERT INTO ingredientes (nombre) VALUES ('Carambola');
INSERT INTO ingredientes (nombre) VALUES ('Mamoncillo');
INSERT INTO ingredientes (nombre) VALUES ('Rambután');
INSERT INTO ingredientes (nombre) VALUES ('Leche');
INSERT INTO ingredientes (nombre) VALUES ('Yogur');
INSERT INTO ingredientes (nombre) VALUES ('Crema');
INSERT INTO ingredientes (nombre) VALUES ('Queso cheddar');
INSERT INTO ingredientes (nombre) VALUES ('Queso mozzarella');
INSERT INTO ingredientes (nombre) VALUES ('Queso parmesano');
INSERT INTO ingredientes (nombre) VALUES ('Queso gouda');
INSERT INTO ingredientes (nombre) VALUES ('Queso suizo');
INSERT INTO ingredientes (nombre) VALUES ('Queso azul');
INSERT INTO ingredientes (nombre) VALUES ('Queso brie');
INSERT INTO ingredientes (nombre) VALUES ('Queso camembert');
INSERT INTO ingredientes (nombre) VALUES ('Queso de cabra');
INSERT INTO ingredientes (nombre) VALUES ('Queso de oveja');
INSERT INTO ingredientes (nombre) VALUES ('Queso crema');
INSERT INTO ingredientes (nombre) VALUES ('Queso ricotta');
INSERT INTO ingredientes (nombre) VALUES ('Queso cottage');
INSERT INTO ingredientes (nombre) VALUES ('Queso feta');
INSERT INTO ingredientes (nombre) VALUES ('Queso queso fresco');
INSERT INTO ingredientes (nombre) VALUES ('Queso roquefort');
INSERT INTO ingredientes (nombre) VALUES ('Queso panela');
INSERT INTO ingredientes (nombre) VALUES ('Arroz');
INSERT INTO ingredientes (nombre) VALUES ('Trigo');
INSERT INTO ingredientes (nombre) VALUES ('Avena');
INSERT INTO ingredientes (nombre) VALUES ('Maíz');
INSERT INTO ingredientes (nombre) VALUES ('Centeno');
INSERT INTO ingredientes (nombre) VALUES ('Cebada');
INSERT INTO ingredientes (nombre) VALUES ('Quinoa');
INSERT INTO ingredientes (nombre) VALUES ('Mijo');
INSERT INTO ingredientes (nombre) VALUES ('Amaranto');
INSERT INTO ingredientes (nombre) VALUES ('Cuscús');
INSERT INTO ingredientes (nombre) VALUES ('Pan de trigo');
INSERT INTO ingredientes (nombre) VALUES ('Harina de maíz');
INSERT INTO ingredientes (nombre) VALUES ('Harina de avena');
INSERT INTO ingredientes (nombre) VALUES ('Harina de trigo');
INSERT INTO ingredientes (nombre) VALUES ('Harina de centeno');
INSERT INTO ingredientes (nombre) VALUES ('Harina de cebada');
INSERT INTO ingredientes (nombre) VALUES ('Harina de quinoa');
INSERT INTO ingredientes (nombre) VALUES ('Harina de amaranto');
INSERT INTO ingredientes (nombre) VALUES ('Filete de ternera');
INSERT INTO ingredientes (nombre) VALUES ('Chuletón');
INSERT INTO ingredientes (nombre) VALUES ('Costillas de res');
INSERT INTO ingredientes (nombre) VALUES ('Carne molida de res');
INSERT INTO ingredientes (nombre) VALUES ('Roast beef');
INSERT INTO ingredientes (nombre) VALUES ('Carne para guisar');
INSERT INTO ingredientes (nombre) VALUES ('Solomillo');
INSERT INTO ingredientes (nombre) VALUES ('Entrecot');
INSERT INTO ingredientes (nombre) VALUES ('Lengua de res');
INSERT INTO ingredientes (nombre) VALUES ('Rabo de res');
INSERT INTO ingredientes (nombre) VALUES ('Tripas de res');
INSERT INTO ingredientes (nombre) VALUES ('Corazón de res');
INSERT INTO ingredientes (nombre) VALUES ('Hígado de res');
INSERT INTO ingredientes (nombre) VALUES ('Riñones de res');
INSERT INTO ingredientes (nombre) VALUES ('Tuétano de res');
INSERT INTO ingredientes (nombre) VALUES ('Carrilleras de res');
INSERT INTO ingredientes (nombre) VALUES ('Morcilla de res');
INSERT INTO ingredientes (nombre) VALUES ('Chorizo de res');
INSERT INTO ingredientes (nombre) VALUES ('Salchicha de res');
INSERT INTO ingredientes (nombre) VALUES ('Carne de res');
INSERT INTO ingredientes (nombre) VALUES ('Cecina de res');
INSERT INTO ingredientes (nombre) VALUES ('Tripas de res para embutidos');
INSERT INTO ingredientes (nombre) VALUES ('Huesos de res para caldo');
INSERT INTO ingredientes (nombre) VALUES ('Tendones de res');
INSERT INTO ingredientes (nombre) VALUES ('Cartílagos de res');
INSERT INTO ingredientes (nombre) VALUES ('Pulmones de res');
INSERT INTO ingredientes (nombre) VALUES ('Lengua de res enlatada');
INSERT INTO ingredientes (nombre) VALUES ('Gelatina de res');
INSERT INTO ingredientes (nombre) VALUES ('Pechuga de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Muslo de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Ala de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Pierna de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Pollo entero');
INSERT INTO ingredientes (nombre) VALUES ('Pavo entero');
INSERT INTO ingredientes (nombre) VALUES ('Pavo molido');
INSERT INTO ingredientes (nombre) VALUES ('Pato entero');
INSERT INTO ingredientes (nombre) VALUES ('Filete de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Jamón de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Pechuga de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Muslo de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Ala de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Pierna de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Pechuga de pollo enlatada');
INSERT INTO ingredientes (nombre) VALUES ('Salchicha de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Salchicha de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Jamón de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Jamón de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Chorizo de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Chorizo de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Salami de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Salami de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Pepperoni de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Pepperoni de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Bacon de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Mortadela de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Mortadela de pavo');
INSERT INTO ingredientes (nombre) VALUES ('Chuleta de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Lomo de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Costilla de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Pechuga de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Solomillo de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Pernil de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Cabeza de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Carnitas de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Tocino de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Jamón de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Salchicha de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Chorizo de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Morcilla de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Panceta de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Hueso de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Hígado de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Riñón de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Trotters de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Callos de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Gelatina de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Grasa de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Casquería de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Fritada de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Chicharrón de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Cabeza de lomo de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Lengua de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Oreja de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Pata de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Rabo de cerdo');
INSERT INTO ingredientes (nombre) VALUES ('Azúcar');
INSERT INTO ingredientes (nombre) VALUES ('Azúcar glas');
INSERT INTO ingredientes (nombre) VALUES ('Azúcar moreno');
INSERT INTO ingredientes (nombre) VALUES ('Azúcar mascabado');
INSERT INTO ingredientes (nombre) VALUES ('Miel');
INSERT INTO ingredientes (nombre) VALUES ('Jarabe de maíz');
INSERT INTO ingredientes (nombre) VALUES ('Jarabe de arce');
INSERT INTO ingredientes (nombre) VALUES ('Chocolate');
INSERT INTO ingredientes (nombre) VALUES ('Chocolate blanco');
INSERT INTO ingredientes (nombre) VALUES ('Chocolate con leche');
INSERT INTO ingredientes (nombre) VALUES ('Chocolate oscuro');
INSERT INTO ingredientes (nombre) VALUES ('Cacao en polvo');
INSERT INTO ingredientes (nombre) VALUES ('Vainilla');
INSERT INTO ingredientes (nombre) VALUES ('Extracto de vainilla');
INSERT INTO ingredientes (nombre) VALUES ('Esencia de vainilla');
INSERT INTO ingredientes (nombre) VALUES ('Canela');
INSERT INTO ingredientes (nombre) VALUES ('Clavo de olor');
INSERT INTO ingredientes (nombre) VALUES ('Jengibre en polvo');
INSERT INTO ingredientes (nombre) VALUES ('Nuez moscada');
INSERT INTO ingredientes (nombre) VALUES ('Almendra');
INSERT INTO ingredientes (nombre) VALUES ('Avellana');
INSERT INTO ingredientes (nombre) VALUES ('Nueces');
INSERT INTO ingredientes (nombre) VALUES ('Pistachos');
INSERT INTO ingredientes (nombre) VALUES ('Dátiles');
INSERT INTO ingredientes (nombre) VALUES ('Pasas');
INSERT INTO ingredientes (nombre) VALUES ('Uvas pasas');
INSERT INTO ingredientes (nombre) VALUES ('Coco rallado');
INSERT INTO ingredientes (nombre) VALUES ('Malvaviscos');
INSERT INTO ingredientes (nombre) VALUES ('Atún');
INSERT INTO ingredientes (nombre) VALUES ('Salmón');
INSERT INTO ingredientes (nombre) VALUES ('Trucha');
INSERT INTO ingredientes (nombre) VALUES ('Merluza');
INSERT INTO ingredientes (nombre) VALUES ('Bacalao');
INSERT INTO ingredientes (nombre) VALUES ('Sardinas');
INSERT INTO ingredientes (nombre) VALUES ('Anchoas');
INSERT INTO ingredientes (nombre) VALUES ('Pulpo');
INSERT INTO ingredientes (nombre) VALUES ('Calamar');
INSERT INTO ingredientes (nombre) VALUES ('Camarones');
INSERT INTO ingredientes (nombre) VALUES ('Langosta');
INSERT INTO ingredientes (nombre) VALUES ('Cangrejo');
INSERT INTO ingredientes (nombre) VALUES ('Mejillones');
INSERT INTO ingredientes (nombre) VALUES ('Agua');
INSERT INTO ingredientes (nombre) VALUES ('Aceite');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de naranja');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de manzana');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de uva');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de piña');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de tomate');
INSERT INTO ingredientes (nombre) VALUES ('Cerveza');
INSERT INTO ingredientes (nombre) VALUES ('Vino tinto');
INSERT INTO ingredientes (nombre) VALUES ('Vino blanco');
INSERT INTO ingredientes (nombre) VALUES ('Café');
INSERT INTO ingredientes (nombre) VALUES ('Vinagre');
INSERT INTO ingredientes (nombre) VALUES ('Tortillas');
INSERT INTO ingredientes (nombre) VALUES ('Frijoles');
INSERT INTO ingredientes (nombre) VALUES ('Frijoles rojos');
INSERT INTO ingredientes (nombre) VALUES ('Frijoles blancos');
INSERT INTO ingredientes (nombre) VALUES ('Frijoles pintos');
INSERT INTO ingredientes (nombre) VALUES ('Garbanzos');
INSERT INTO ingredientes (nombre) VALUES ('Lentejas');
INSERT INTO ingredientes (nombre) VALUES ('Habas');
INSERT INTO ingredientes (nombre) VALUES ('Judías verdes');
INSERT INTO ingredientes (nombre) VALUES ('Alubias');
INSERT INTO ingredientes (nombre) VALUES ('Soja');
INSERT INTO ingredientes (nombre) VALUES ('Cacahuetes');
INSERT INTO ingredientes (nombre) VALUES ('Chícharos');
INSERT INTO ingredientes (nombre) VALUES ('Polvo para hornear');
INSERT INTO ingredientes (nombre) VALUES ('Bicarbonato de sodio');
INSERT INTO ingredientes (nombre) VALUES ('Sal');
INSERT INTO ingredientes (nombre) VALUES ('Huevo');
INSERT INTO ingredientes (nombre) VALUES ('Mantequilla');
INSERT INTO ingredientes (nombre) VALUES ('Lechuga romana');
INSERT INTO ingredientes (nombre) VALUES ('Crutones');
INSERT INTO ingredientes (nombre) VALUES ('Dientes de ajo');
INSERT INTO ingredientes (nombre) VALUES ('Caldo de verduras');
INSERT INTO ingredientes (nombre) VALUES ('Pimienta negra molida');
INSERT INTO ingredientes (nombre) VALUES ('Comino molido');
INSERT INTO ingredientes (nombre) VALUES ('Pimentón');
INSERT INTO ingredientes (nombre) VALUES ('Aceite de oliva');
INSERT INTO ingredientes (nombre) VALUES ('Yogur natural');
INSERT INTO ingredientes (nombre) VALUES ('Leche de almendra');
INSERT INTO ingredientes (nombre) VALUES ('Caldo de pollo');
INSERT INTO ingredientes (nombre) VALUES ('Mantequilla sin sal');
INSERT INTO ingredientes (nombre) VALUES ('Levadura en polvo');
INSERT INTO ingredientes (nombre) VALUES ('Harina');
INSERT INTO ingredientes (nombre) VALUES ('Manteca');
INSERT INTO ingredientes (nombre) VALUES ('Hoja de laurel');
INSERT INTO ingredientes (nombre) VALUES ('Tortilla de maíz');
INSERT INTO ingredientes (nombre) VALUES ('Quinoa cocida');
INSERT INTO ingredientes (nombre) VALUES ('Cilantro picado');
INSERT INTO ingredientes (nombre) VALUES ('Pasta');
INSERT INTO ingredientes (nombre) VALUES ('Agua de coco');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de limón');
INSERT INTO ingredientes (nombre) VALUES ('Mermelada de albaricoque');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de limón verde');
INSERT INTO ingredientes (nombre) VALUES ('Jalapeño');
INSERT INTO ingredientes (nombre) VALUES ('Cebolla roja');
INSERT INTO ingredientes (nombre) VALUES ('Pan de hamburguesa');
INSERT INTO ingredientes (nombre) VALUES ('Pan rallado');
INSERT INTO ingredientes (nombre) VALUES ('Pechuga de pollo molida');
INSERT INTO ingredientes (nombre) VALUES ('Lata de tomates en cubitos');
INSERT INTO ingredientes (nombre) VALUES ('Pechuga de pollo cocida');
INSERT INTO ingredientes (nombre) VALUES ('Queso rallado');
INSERT INTO ingredientes (nombre) VALUES ('Tomatillo');
INSERT INTO ingredientes (nombre) VALUES ('Azúcar granulada');
INSERT INTO ingredientes (nombre) VALUES ('Aceite vegetal');
INSERT INTO ingredientes (nombre) VALUES ('Mayonesa');
INSERT INTO ingredientes (nombre) VALUES ('Mostaza');
INSERT INTO ingredientes (nombre) VALUES ('Pepinillos');
INSERT INTO ingredientes (nombre) VALUES ('Aceitunas negras');
INSERT INTO ingredientes (nombre) VALUES ('Arroz de sushi');
INSERT INTO ingredientes (nombre) VALUES ('Vinagre de arroz');
INSERT INTO ingredientes (nombre) VALUES ('Filete de salmón');
INSERT INTO ingredientes (nombre) VALUES ('Hojas de alga nori');
INSERT INTO ingredientes (nombre) VALUES ('Jugo de lima');
INSERT INTO ingredientes (nombre) VALUES ('Chorizo argentino');
INSERT INTO ingredientes (nombre) VALUES ('Morcillas argentinas');
INSERT INTO ingredientes (nombre) VALUES ('Provoleta');
INSERT INTO ingredientes (nombre) VALUES ('Láminas de lasaña');
INSERT INTO ingredientes (nombre) VALUES ('Salsa de tomate');
INSERT INTO ingredientes (nombre) VALUES ('Hojas de albahaca');
INSERT INTO ingredientes (nombre) VALUES ('Queso mascarpone');
INSERT INTO ingredientes (nombre) VALUES ('Café espresso');
INSERT INTO ingredientes (nombre) VALUES ('Brandy');
INSERT INTO ingredientes (nombre) VALUES ('Galletas de savoiardi');
INSERT INTO ingredientes (nombre) VALUES ('Lomo de res');
INSERT INTO ingredientes (nombre) VALUES ('Pimiento amarillo');
INSERT INTO ingredientes (nombre) VALUES ('Salsa de soja');
INSERT INTO ingredientes (nombre) VALUES ('Vinagre blanco');
INSERT INTO ingredientes (nombre) VALUES ('Ajil amarillo molido');
INSERT INTO ingredientes (nombre) VALUES ('Filete de pescado blanco');
INSERT INTO ingredientes (nombre) VALUES ('Paprika');
INSERT INTO ingredientes (nombre) VALUES ('Arroz de Arborio');
INSERT INTO ingredientes (nombre) VALUES ('Jamón de pierna');