INSERT INTO pasos (Recetas_idRecetas, nopaso, paso)
VALUES  (1, '1', 'En un tazón grande, mezcla la harina, el azúcar, el polvo de hornear, el bicarbonato de sodio y la sal.'),
        (1, '2', 'En otro tazón, bate los huevos y luego agrega la leche y el extracto de vainilla. Mezcla bien.'),
        (1, '3', 'Añade los ingredientes líquidos a los ingredientes secos y mezcla hasta que estén bien combinados. No te preocupes si la masa tiene algunos grumos, es normal en los pancakes.'),
        (1, '4', 'Con una cuchara de helado o una cuchara grande, vierte porciones de masa en una sartén caliente previamente engrasada con aceite o mantequilla, a fuego medio-bajo.'),
        (1, '5', 'Espolvorea algunos arándanos sobre cada pancake en la sartén. Cocina hasta que aparezcan burbujas en la superficie de los pancakes y los bordes estén ligeramente dorados, aproximadamente 2-3 minutos.'),
        (1, '6', 'Voltea los pancakes y cocina por otros 1-2 minutos hasta que estén dorados en el otro lado y los arándanos estén jugosos.'),
        (1, '7', 'Repite el proceso con el resto de la masa hasta que hayas utilizado toda la mezcla.'),
        (1, '8', 'Sirve los pancakes de arándanos calientes con sirope de arce, mantequilla derretida, crema batida o más arándanos frescos como topping, si lo deseas.'),

        (2, '1', 'En un tazón grande, mezcla la lechuga romana, los crutones y el queso parmesano.'),
        (2, '2', 'En otro tazón pequeño, mezcla la mayonesa, el aceite de oliva, la salsa Worcestershire, la mostaza Dijon, el ajo picado, el jugo de limón y la salsa de anchoas (si la estás usando). Remueve bien para que todos los ingredientes se mezclen.'),
        (2, '3', 'Vierte el aderezo sobre la ensalada y mezcla suavemente para que todo esté bien cubierto. Agrega sal y pimienta al gusto.'),
        (2, '4', 'Sirve la ensalada César en platos individuales y espolvorea un poco más de queso parmesano rallado por encima, si lo deseas.'),

        (3, '1', 'En una olla grande, calienta el aceite de oliva a fuego medio. Agrega la cebolla y el ajo, y cocina hasta que estén tiernos y fragantes, aproximadamente 5 minutos.'),
        (3, '2', 'Añade los tomates, la zanahoria y la papa a la olla. Cocina por otros 5 minutos, revolviendo ocasionalmente.'),
        (3, '3', 'Agrega el caldo de verduras, el azúcar, la sal, la pimienta, el comino y el pimentón (si lo estás usando) a la olla. Lleva la sopa a ebullición, luego reduce el fuego y deja que hierva a fuego lento durante unos 15-20 minutos, o hasta que las verduras estén tiernas.'),
        (3, '4', 'Retira la olla del fuego y deja que la sopa se enfríe ligeramente. Luego, utiliza una licuadora o una batidora de inmersión para triturar la sopa hasta obtener una consistencia suave.'),
        (3, '5', 'Vuelve a calentar la sopa a fuego medio-bajo antes de servir. Sirve caliente en tazones individuales.'),
        (3, '6', 'Opcionalmente, puedes espolvorear albahaca fresca picada y queso parmesano rallado por encima antes de servir.'),

        (4, '1', 'Pela y corta el plátano en rodajas.'),
        (4, '2', 'En una licuadora, coloca el plátano, las fresas, el mango, el yogur y la leche de almendra.'),
        (4, '3', 'Licúa todo a velocidad alta hasta obtener una mezcla suave y cremosa.'),
        (4, '4', 'Prueba el smoothie y si lo deseas, puedes endulzarlo con miel a tu gusto.'),
        (4, '5', 'Sirve el smoothie de frutas en un vaso y disfrútalo de inmediato.'),

        (5, '1', 'Precalienta el horno a 180°C (350°F).'),
        (5, '2', 'Lava y seca el lomo de cerdo con papel absorbente.'),
        (5, '3', 'En un tazón pequeño, mezcla el aceite de oliva, la sal, la pimienta, el romero, el tomillo y el ajo picado para hacer una marinada.'),
        (5, '4', 'Frota el lomo de cerdo con la marinada, asegurándote de cubrirlo por completo.'),
        (5, '5', 'Coloca el lomo de cerdo en una fuente de hornear o en una bandeja para hornear y añade el caldo de pollo o de cerdo en el fondo de la fuente.'),
        (5, '6', 'Opcionalmente, puedes agregar vino blanco a la fuente para darle más sabor al lomo de cerdo.'),
        (5, '7', 'Cubre la fuente con papel de aluminio y hornea durante aproximadamente 1 hora y 30 minutos, o hasta que la temperatura interna del lomo de cerdo alcance los 70°C (160°F) en un termómetro de cocina.'),
        (5, '8', 'Retira el papel de aluminio durante los últimos 15-20 minutos de cocción para dorar la parte superior del lomo de cerdo.'),
        (5, '9', 'Retira el lomo de cerdo del horno y deja que repose durante unos minutos antes de cortarlo en rodajas.'),
        (5, '10', 'Sirve el lomo de cerdo al horno con su jugo de cocción por encima y acompáñalo con tus guarniciones favoritas, como puré de papas, verduras asadas o una ensalada.'),

        (6, '1', 'Precalienta tu horno a 180°C y engrasa un molde redondo de unos 22 cm de diámetro.'),
        (6, '2', 'En un tazón grande, derrite el chocolate negro y la mantequilla en el microondas o a baño maría, revolviendo ocasionalmente hasta que estén completamente derretidos y suaves.'),
        (6, '3', 'Agrega el azúcar al tazón con el chocolate derretido y mezcla bien. Luego, incorpora los huevos uno por uno, mezclando bien después de cada adición. Añade el extracto de vainilla y mezcla nuevamente.'),
        (6, '4', 'Tamiza la harina, la levadura en polvo y la sal en el tazón con la mezcla de chocolate y mezcla todo hasta obtener una masa suave y homogénea.'),
        (6, '5', 'Vierte la masa en el molde previamente engrasado y nivelar la superficie con una espátula.'),
        (6, '6', 'Hornea el pastel en el horno precalentado durante aproximadamente 25-30 minutos, o hasta que esté cocido. Puedes comprobar la cocción insertando un palillo en el centro del pastel; si sale limpio o con algunas migas húmedas, el pastel está listo.'),
        (6, '7', 'Retira el pastel del horno y déjalo enfriar en el molde durante unos minutos antes de desmoldarlo sobre una rejilla para que se enfríe por completo.'),
        (6, '8', 'Una vez que el pastel esté completamente frío, puedes espolvorear azúcar glas por encima para decorar, si lo deseas. ¡Y listo! Ahora puedes disfrutar de un delicioso pastel de chocolate casero para 8 personas.'),

        (7, '1', 'Corta la carne de cerdo en trozos grandes, aproximadamente de 5-7 cm de tamaño.'),
        (7, '2', 'En una olla grande a fuego medio-alto, derrite la manteca de cerdo o calienta el aceite vegetal. Agrega la carne de cerdo y dórala por todos los lados hasta que esté bien dorada.'),
        (7, '3', 'Añade la sal, la pimienta negra molida, el comino, el orégano y el pimiento de cayena (si lo usas) a la olla con la carne de cerdo dorada. Mezcla bien.'),
        (7, '4', 'Agrega la hoja de laurel, los cuartos de naranja y el agua a la olla. Lleva a ebullición.'),
        (7, '5', 'Reduce el fuego a bajo y cubre la olla. Cocina las carnitas a fuego lento durante aproximadamente 2-3 horas, o hasta que la carne esté tierna y se pueda desmenuzar fácilmente con un tenedor.'),
        (7, '6', 'Una vez que la carne esté cocida, retira la hoja de laurel y desmenuza la carne con dos tenedores. Luego, aumenta el fuego a medio-alto y cocina las carnitas desmenuzadas durante otros 5-10 minutos, revolviendo ocasionalmente, para que se doren un poco.'),
        (7, '7', 'Para armar los tacos, calienta las tortillas de maíz en una sartén caliente o en un comal. Coloca una porción de carnitas desmenuzadas en el centro de cada tortilla.'),
        (7, '8', 'Decora los tacos de carnitas con cebolla picada, cilantro picado y salsa de tu preferencia. Exprime un poco de jugo de limón fresco por encima.'),
        (7, '9', 'Sirve los tacos de carnitas calientes y disfrútalos junto con tus acompañamientos favoritos, como frijoles, arroz o guacamole.'),

        (8, '1', 'Enjuaga bien la quinoa cocida bajo agua fría para quitarle el sabor amargo y escúrrela.'),
        (8, '2', 'En un tazón grande, mezcla la quinoa cocida, el pepino, el pimiento rojo, la zanahoria rallada, la cebolla roja y el cilantro fresco picado.'),
        (8, '3', 'En un tazón pequeño, mezcla el jugo de limón, el aceite de oliva, la sal y la pimienta para hacer el aderezo.'),
        (8, '4', 'Vierte el aderezo sobre la ensalada de quinoa y mezcla bien para que todos los ingredientes estén bien cubiertos.'),
        (8, '5', 'Prueba y ajusta la sazón con más sal y pimienta si es necesario.'),
        (8, '6', 'Sirve la ensalada de quinoa en porciones individuales y disfrútala como acompañamiento o como plato principal.'),

        (9, '1', 'Cocina la pasta según las instrucciones del paquete en una olla grande con agua hirviendo con sal. Luego, escúrrela y reserva.'),
        (9, '2', 'En una sartén grande, derrite 1/2 taza de mantequilla a fuego medio-alto. Agrega el pollo y cocina hasta que esté dorado y cocido por completo. Luego, retira el pollo de la sartén y reserva.'),
        (9, '3', 'En la misma sartén, agrega el resto de la mantequilla y derrítela a fuego medio. Agrega el ajo picado y cocina por 1 minuto, hasta que esté fragante pero no dorado.'),
        (9, '4', 'Añade la crema para batir a la sartén con el ajo y la mantequilla, y cocina a fuego medio-bajo durante unos 5 minutos, revolviendo ocasionalmente.'),
        (9, '5', 'Agrega el queso parmesano rallado a la sartén con la crema, el ajo y la mantequilla. Revuelve bien hasta que el queso se haya derretido y la salsa esté suave y espesa.'),
        (9, '6', 'Agrega la nuez moscada molida a la salsa y mezcla bien. Luego, agrega el pollo cocido a la salsa y revuelve para cubrirlo con la salsa.'),
        (9, '7', 'Agrega la pasta cocida a la sartén con la salsa y el pollo. Revuelve todo para que la pasta quede bien cubierta con la salsa.'),
        (9, '8', 'Cocina la pasta y la salsa juntas por unos minutos a fuego medio-bajo, revolviendo ocasionalmente, hasta que esté bien caliente.'),
        (9, '9', 'Prueba la salsa y sazona con sal y pimienta al gusto.'),
        (9, '10', 'Sirve la Pasta Alfredo con Pollo caliente en platos individuales. Puedes decorar con un poco de perejil fresco picado por encima, si lo deseas.'),

        (10, '1', 'Lava bien las espinacas y colócalas en la licuadora.'),
        (10, '2', 'Agrega el pepino, la piña, el plátano, el jengibre rallado y el jugo de limón en la licuadora.'),
        (10, '3', 'Añade el agua de coco o el agua filtrada.'),
        (10, '4', 'Opcionalmente, puedes agregar hielo si quieres que el smoothie esté más frío.'),
        (10, '5', 'Licúa todos los ingredientes a alta velocidad hasta obtener una mezcla suave y homogénea.'),
        (10, '6', 'Vierte el smoothie en un vaso y sírvelo de inmediato.'),
        (10, '7', '¡Disfruta de tu delicioso y saludable Smoothie Verde Detox!'),

        (11, '1', 'Preparar la masa: En un tazón grande, mezclar la harina, la sal y el azúcar. Disolver la levadura fresca en el agua tibia y agregarla a la mezcla de harina. Mezclar bien hasta obtener una masa suave y elástica. Amasar la masa en una superficie enharinada durante unos 5-7 minutos. Formar una bola con la masa y dejar reposar en un tazón cubierto con un paño húmedo durante aproximadamente 1 hora, o hasta que la masa haya duplicado su tamaño.'),
        (11, '2', 'Preparar la salsa de tomate: En una sartén, calentar el aceite de oliva a fuego medio. Añadir el ajo picado y cocinar por unos minutos hasta que esté dorado. Agregar los tomates picados, el azúcar, la sal y el orégano. Cocinar a fuego lento durante unos 20-25 minutos, o hasta que la salsa se haya espesado. Retirar del fuego y dejar enfriar.'),
        (11, '3', 'Precalentar el horno: Precalentar el horno a 230°C (450°F) y colocar una piedra de pizza en el horno si se tiene una, de lo contrario, una bandeja para hornear.'),
        (11, '4', 'Estirar la masa: Una vez que la masa haya reposado y duplicado su tamaño, amasarla ligeramente en una superficie enharinada. Luego, dividir la masa en 8 porciones iguales y formar bolas con cada porción. Estirar cada bola de masa con un rodillo o con las manos, dando forma redonda o rectangular, según tus preferencias.'),
        (11, '5', 'Armar la pizza: Colocar cada porción de masa estirada en una bandeja para pizza o en la piedra de pizza precalentada. Extender una capa generosa de salsa de tomate sobre la masa, dejando un borde de aproximadamente 1 cm. Espolvorear queso mozzarella rallado sobre la salsa de tomate.'),
        (11, '6', 'Hornear la pizza: Colocar las pizzas en el horno precalentado y hornear durante aproximadamente 10-12 minutos, o hasta que los bordes estén dorados y el queso esté derretido y burbujeante.'),
        (11, '7', 'Servir: Sacar las pizzas del horno y dejar enfriar ligeramente. Decorar con hojas de albahaca fresca.'),

        (12, '1', 'Preparar la masa: En un tazón, mezclar la harina, el azúcar y la sal. Agregar la mantequilla fría y mezclar con un tenedor o con las manos hasta obtener una textura arenosa. Agregar el huevo y amasar ligeramente hasta formar una masa suave. Envolver la masa en papel film y refrigerar durante al menos 30 minutos.'),
        (12, '2', 'Precalentar el horno: Precalentar el horno a 180°C (350°F) y engrasar ligeramente un molde para tarta de aproximadamente 23 cm (9 pulgadas) de diámetro.'),
        (12, '3', 'Estirar la masa: Sacar la masa del refrigerador y estirarla en una superficie enharinada hasta que tenga un grosor de aproximadamente 3-4 mm. Transferir la masa al molde para tarta, presionando suavemente en el fondo y los bordes del molde. Cortar el exceso de masa en los bordes.'),
        (12, '4', 'Preparar el relleno: En un tazón, mezclar las rodajas de manzana con el azúcar, la canela, la nuez moscada y el jugo de limón. Mezclar bien para que las manzanas queden bien cubiertas con el azúcar y las especias.'),
        (12, '5', 'Armar la tarta: Colocar las rodajas de manzana en la masa de tarta preparada, en una capa uniforme, cubriendo todo el fondo de la tarta.'),
        (12, '6', 'Hornear la tarta: Hornear la tarta en el horno precalentado durante aproximadamente 35-40 minutos, o hasta que la masa esté dorada y las manzanas estén tiernas.'),
        (12, '7', 'Preparar el glaseado (opcional): Mientras la tarta está todavía caliente, mezclar la mermelada de albaricoque o melocotón con el agua caliente para hacer el glaseado. Pintar ligeramente la superficie de la tarta con el glaseado para darle un brillo extra.'),
        (12, '8', 'Servir: Dejar enfriar la tarta ligeramente antes de cortarla en porciones y servirla. Se puede servir sola o acompañada de una bola de helado de vainilla o crema batida, ¡y disfrutar de esta deliciosa tarta de manzana casera!'),

        (13, '1', 'Lava los camarones con agua fría y escúrrelos bien.'),
        (13, '2', 'En un recipiente de vidrio o cerámica, coloca los camarones y cúbrelos con el jugo de limón fresco y el jugo de limón verde. Asegúrate de que los camarones estén completamente sumergidos en el jugo de limón. Deja reposar en el refrigerador durante al menos 30 minutos o hasta que los camarones estén rosados y opacos.'),
        (13, '3', 'En otro recipiente, mezcla la cebolla roja, el jalapeño o ají, el tomate, el aguacate y el cilantro. Agrega la sal y la pimienta negra molida, y mezcla bien.'),
        (13, '4', 'Una vez que los camarones estén listos, escúrrelos del jugo de limón y agrégales la mezcla de cebolla, jalapeño, tomate, aguacate y cilantro. Mezcla todo suavemente.'),
        (13, '5', 'Sirve el ceviche de camarón en platos individuales o en una fuente para compartir. Puedes acompañarlo con tortillas de maíz, tostadas o galletas saladas. ¡Disfruta de este delicioso platillo fresco y lleno de sabor!'),

        (14, '1', 'En un tazón grande, mezcla la carne de pollo molida con el huevo, el pan rallado, la cebolla picada, el ajo picado, el perejil picado, la sal y la pimienta. Mezcla bien todos los ingredientes hasta obtener una mezcla homogénea.'),
        (14, '2', 'Divide la mezcla de pollo en 4 porciones iguales y forma hamburguesas con las manos, dándoles forma redonda y aplanada.'),
        (14, '3', 'Calienta una sartén antiadherente a fuego medio-alto y agrega un poco de aceite o mantequilla para engrasarla.'),
        (14, '4', 'Coloca las hamburguesas de pollo en la sartén caliente y cocina por aproximadamente 4-5 minutos por cada lado, o hasta que estén doradas y cocidas por completo en el centro. Asegúrate de que alcancen una temperatura interna de al menos 75°C (165°F) para asegurarte de que estén completamente cocidas.'),
        (14, '5', 'Mientras las hamburguesas se cocinan, puedes tostar ligeramente los panes de hamburguesa en una parrilla o en una sartén caliente.'),
        (14, '6', 'Una vez que las hamburguesas de pollo estén cocidas, retíralas del fuego y deja que descansen unos minutos.'),
        (14, '7', 'Para armar las hamburguesas, coloca las hamburguesas de pollo en los panes tostados y agrega hojas de lechuga, rodajas de tomate y otros ingredientes de tu preferencia.'),
        (14, '8', '¡Sirve tus deliciosas hamburguesas de pollo caseras y disfruta!'),

        (15, '1', 'Calienta el aceite de oliva en una olla grande a fuego medio. Agrega la cebolla, el ajo, las zanahorias, el apio y el pimiento rojo. Cocina hasta que las verduras estén tiernas, aproximadamente de 5 a 7 minutos.'),
        (15, '2', 'Agrega las lentejas enjuagadas y escurridas a la olla, junto con el caldo de verduras o caldo de pollo, los tomates en cubitos, el tomillo, el comino y la hoja de laurel. Lleva la mezcla a ebullición.'),
        (15, '3', 'Reduce el fuego a bajo y cocina a fuego lento, tapando la olla parcialmente, durante aproximadamente 25-30 minutos, o hasta que las lentejas estén tiernas.'),
        (15, '4', 'Retira la hoja de laurel y sazona la sopa con sal y pimienta al gusto.'),
        (15, '5', 'Agrega las espinacas picadas a la olla y cocina por unos minutos hasta que se marchiten.'),
        (15, '6', 'Sirve la sopa de lentejas caliente en tazones individuales. Si lo deseas, puedes espolvorear un poco de queso rallado por encima antes de servir.'),

        (16, '1', 'Precalienta el horno a 180°C (350°F).'),
        (16, '2', 'Lava los tomatillos verdes y colócalos en una olla con agua hirviendo. Cocina a fuego medio-alto hasta que estén suaves y hayan cambiado de color, aproximadamente 8-10 minutos. Retira del agua y deja enfriar.'),
        (16, '3', 'Mientras los tomatillos se enfrían, puedes preparar el relleno de pollo. En un tazón, mezcla las pechugas de pollo desmenuzadas con 1/2 taza de salsa verde y 1/2 taza de queso rallado.'),
        (16, '4', 'Para preparar la salsa verde, coloca los tomatillos cocidos, el chile jalapeño, el ajo, la cebolla, el cilantro, el jugo de limón, la sal y el azúcar (si lo usas) en una licuadora o procesador de alimentos. Mezcla hasta obtener una salsa suave y homogénea.'),
        (16, '5', 'En una sartén antiadherente, calienta una cucharada de aceite a fuego medio-alto. Sumerge cada tortilla de maíz en la salsa verde para ablandarla y colócala en la sartén caliente. Cocina por unos segundos por cada lado, solo para que se ablanden, y luego colócalas en un plato.'),
        (16, '6', 'Coloca aproximadamente 2 cucharadas del relleno de pollo en el centro de cada tortilla de maíz y enróllalas apretadamente. Coloca las enchiladas rellenas en un refractario para horno.'),
        (16, '7', 'Cubre las enchiladas con el resto de la salsa verde y espolvorea el queso rallado restante por encima.'),
        (16, '8', 'Hornea las enchiladas en el horno precalentado durante 15-20 minutos, o hasta que el queso esté derretido y burbujeante.'),
        (16, '9', 'Sirve las enchiladas verdes calientes, decoradas con crema agria y hojas de cilantro fresco'),

        (17, '1', 'Precalienta tu horno a 180°C (350°F) y engrasa y enharina un molde para pastel de 9 pulgadas.'),
        (17, '2', 'En un tazón grande, mezcla las zanahorias ralladas, el azúcar y el aceite vegetal. Agrega los huevos uno a uno, batiendo bien después de cada adición.'),
        (17, '3', 'En otro tazón, tamiza la harina, el polvo para hornear, el bicarbonato de sodio, la sal y la canela. Agrega los ingredientes secos a la mezcla de zanahoria y mezcla bien.'),
        (17, '4', 'Vierte la masa en el molde preparado y hornea en el horno precalentado durante aproximadamente 35-40 minutos, o hasta que un palillo insertado en el centro del pastel salga limpio.'),
        (17, '5', 'Retira el pastel del horno y déjalo enfriar en el molde durante unos 10 minutos, luego desmóldalo y déjalo enfriar completamente sobre una rejilla.'),
        (17, '6', 'Si deseas, puedes preparar el glaseado de queso crema. En un tazón, bate el queso crema y la mantequilla hasta que estén suaves y cremosos. Agrega el azúcar glas en varias adiciones y sigue batiendo hasta obtener una consistencia suave. Finalmente, añade el extracto de vainilla y mezcla bien.'),
        (17, '7', 'Una vez que el pastel esté completamente frío, puedes cubrirlo con el glaseado de queso crema, o simplemente decorarlo con zanahorias ralladas o nueces picadas, si lo deseas.'),

        (18, '1', 'En un tazón grande, mezcla la mayonesa, la mostaza y el jugo de limón para hacer la salsa.'),
        (18, '2', 'Agrega el atún escurrido al tazón con la salsa y mezcla bien para que el atún quede cubierto con la salsa.'),
        (18, '3', 'Añade la cebolla picada, el apio, los pepinillos y las aceitunas al tazón y mezcla todo.'),
        (18, '4', 'Sazona con sal y pimienta al gusto y vuelve a mezclar.'),
        (18, '5', 'Divide la lechuga mixta en dos platos para servir.'),
        (18, '6', 'Coloca la ensalada de atún encima de la lechuga en cada plato.'),
        (18, '7', 'Sirve la ensalada de atún y disfrútala como una deliciosa comida o cena fresca y saludable.'),

        (19, '1', 'Cocina la pasta al dente en una olla grande con agua hirviendo y sal, siguiendo las instrucciones del paquete. Escúrrela y reserva una taza del agua de cocción de la pasta.'),
        (19, '2', 'Mientras se cuece la pasta, en una sartén grande a fuego medio-bajo, calienta un poco de aceite de oliva y añade la panceta o tocino. Cocina hasta que esté dorado y crujiente. Luego, agrega el ajo picado y cocina por 1 minuto hasta que esté fragante. Retira la sartén del fuego.'),
        (19, '3', 'En un tazón grande, bate los huevos con la mitad del queso parmesano rallado y la mitad del queso pecorino rallado. Agrega una generosa cantidad de pimienta negra molida y mezcla bien.'),
        (19, '4', 'Añade la pasta cocida y escurrida a la sartén con la panceta o tocino y el ajo. Remueve todo para que la pasta quede bien cubierta con la grasa de la panceta.'),
        (19, '5', 'Luego, agrega la mezcla de huevo y queso a la sartén con la pasta caliente. Remueve rápidamente para que la salsa se espese y se mezcle con la pasta, pero sin que los huevos se cocinen demasiado y se conviertan en revuelto. Si la salsa está demasiado espesa, puedes agregar un poco del agua de cocción de la pasta reservada para aligerarla.'),
        (19, '6', 'Sirve la pasta carbonara en platos individuales y espolvorea por encima el queso parmesano y pecorino rallados restantes. Añade más pimienta negra molida al gusto, y ¡a disfrutar de esta clásica y deliciosa receta de pasta carbonara!'),

        (20, '1', 'Pela y corta el mango en trozos, desechando el hueso.'),
        (20, '2', 'En una licuadora, coloca los trozos de mango, el yogur natural, la leche y la miel (si lo deseas).'),
        (20, '3', 'Agrega hielo al gusto para obtener una consistencia más espesa y refrescante.'),
        (20, '4', 'Licúa todo a velocidad alta hasta que obtengas una mezcla suave y homogénea.'),
        (20, '5', 'Prueba el smoothie y ajusta la cantidad de miel si es necesario, según tu preferencia de dulzor.'),
        (20, '6', 'Sirve en un vaso y disfruta de tu delicioso smoothie de mango.'),

        (21, '1', 'Lava el arroz de sushi bajo agua fría hasta que el agua salga clara. Luego, cocínalo siguiendo las instrucciones del paquete o en una arrocera, usando las 2 1/4 tazas de agua.'),
        (21, '2', 'Mientras el arroz se cocina, mezcla el vinagre de arroz, el azúcar y la sal en un tazón pequeño. Reserva.'),
        (21, '3', 'Una vez que el arroz esté cocido, colócalo en un tazón grande y añade la mezcla de vinagre de arroz. Remueve suavemente el arroz con una cuchara de madera o una espátula de arroz, realizando movimientos de abajo hacia arriba, para distribuir la mezcla de vinagre de arroz de manera uniforme. Deja que el arroz se enfríe a temperatura ambiente.'),
        (21, '4', 'Mientras tanto, prepara los ingredientes del relleno cortando el salmón, el aguacate y el pepino en tiras delgadas.'),
        (21, '5', 'Para armar los rollos de sushi, coloca una hoja de alga nori sobre una esterilla de bambú para sushi (o envoltura de plástico si no tienes una esterilla) con el lado brillante hacia abajo.'),
        (21, '6', 'Humedece tus manos con agua fría para evitar que el arroz se pegue y toma aproximadamente 1/4 de taza de arroz de sushi cocido. Extiende el arroz uniformemente sobre la hoja de alga nori, dejando un espacio vacío de aproximadamente 2 cm en el borde superior.'),
        (21, '7', 'Coloca tiras de salmón, aguacate y pepino en el centro del arroz.'),
        (21, '8', 'Usando la esterilla de bambú (o envoltura de plástico), enrolla el sushi firmemente, aplicando una ligera presión para asegurarte de que los ingredientes se mantengan en su lugar.'),
        (21, '9', 'Repite el proceso para hacer más rollos de sushi.'),
        (21, '10', 'Con un cuchillo afilado, corta cada rollo en rodajas de aproximadamente 2,5 cm de ancho.'),
        (21, '11', 'Sirve el sushi de salmón con salsa de soja para mojar, y si lo deseas, wasabi y jengibre encurtido.'),

        (22, '1', 'Limpia y lava el pulpo fresco. Puedes pedirle a tu pescadero que lo limpie y retire la piel externa, o hacerlo tú mismo en casa. Retira los ojos y la boca del pulpo, y enjuágalo bien bajo agua fría.'),
        (22, '2', 'Hierve agua en una olla grande con una pizca de sal. Cuando el agua esté hirviendo, sumerge el pulpo en el agua y cocínalo a fuego medio-alto durante aproximadamente 30-45 minutos, o hasta que esté tierno. El tiempo de cocción puede variar dependiendo del tamaño del pulpo, así que asegúrate de probar la textura con un tenedor para asegurarte de que esté suave pero no excesivamente blando.'),
        (22, '3', 'Una vez que el pulpo esté cocido, retíralo del agua y déjalo enfriar a temperatura ambiente. Luego, corta el pulpo en rodajas finas o en trozos pequeños, según tu preferencia, y colócalo en un tazón grande.'),
        (22, '4', 'Agrega el jugo de limón y lima frescos al tazón con el pulpo. El ácido de los cítricos "cocinará" el pulpo, haciéndolo más tierno y dándole un delicioso sabor cítrico. Remueve bien para asegurarte de que el pulpo esté bien cubierto con el jugo de limón y lima. Deja reposar durante unos 10-15 minutos para que el pulpo se marine en los jugos cítricos.'),
        (22, '5', 'Mientras el pulpo se marina, puedes preparar los otros ingredientes. Picar finamente la cebolla roja, el pimiento jalapeño y el cilantro. Si deseas agregar aguacate, pelarlo y cortarlo en cubos.'),
        (22, '6', 'Después de marinar el pulpo, agrega la cebolla roja, el pimiento jalapeño y el cilantro al tazón con el pulpo. Agrega también el aceite de oliva extra virgen. Mezcla bien todos los ingredientes.'),
        (22, '7', 'Prueba el ceviche de pulpo y ajusta la sazón con sal y pimienta al gusto.'),
        (22, '8', 'Si deseas agregar aguacate, puedes hacerlo en este momento y mezclar suavemente para que los cubos de aguacate no se deshagan.'),
        (22, '9', 'Sirve el ceviche de pulpo en platos individuales o en un tazón grande para compartir. Puedes decorar con hojas de cilantro.'),

        (23, '1', 'Preparar el fuego en la parrilla y esperar a que las brasas estén en su punto adecuado para cocinar a fuego medio-alto.'),
        (23, '2', 'Mientras tanto, sazonar la carne de res con sal gruesa por ambos lados. Esto se hace tradicionalmente en Argentina antes de cocinar la carne en la parrilla, y permite resaltar el sabor natural de la carne.'),
        (23, '3', 'Colocar los chorizos y morcillas en la parrilla. Cocinarlos a fuego medio-alto hasta que estén bien cocidos y dorados por fuera. Los chorizos suelen cocinarse más rápido que las morcillas, así que puedes retirarlos antes si es necesario.'),
        (23, '4', 'Agregar los cortes de carne de res a la parrilla. Cocinarlos a fuego medio-alto hasta que estén al punto de cocción deseado. El tiempo de cocción variará dependiendo del grosor de las piezas y del nivel de cocción que prefieras (punto, jugoso o bien cocido). Asegúrate de voltear la carne una vez durante la cocción para que se cocine de manera pareja por ambos lados.'),
        (23, '5', 'En los últimos minutos de cocción, colocar una provoleta sobre cada corte de carne de res. Dejar que el queso se derrita ligeramente y se ponga burbujeante.'),
        (23, '6', 'Retirar los chorizos, morcillas, cortes de carne de res y provoletas de la parrilla y colocarlos en una tabla de cortar para reposar durante unos minutos.'),
        (23, '7', 'Cortar la carne de res en rodajas diagonales y servir en una fuente grande de servir, junto con los chorizos, morcillas y provoletas.'),
        (23, '8', 'Acompañar con chimichurri, que es una salsa tradicional argentina hecha con perejil, ajo, vinagre, aceite de oliva y especias. Puedes servir el chimichurri en un tazón aparte o rociarlo sobre la carne antes de servir.'),
        (23, '9', '¡Disfrutar de una deliciosa parrillada argentina junto a tus amigos y familiares!'),

        (24, '1', 'Precalentar el horno a 180°C (350°F).'),
        (24, '2', 'En una sartén grande a fuego medio-alto, calentar un poco de aceite de oliva. Añadir la cebolla, el ajo y la zanahoria rallada. Cocinar por unos 5 minutos hasta que estén tiernos.'),
        (24, '3', 'Añadir la carne molida de res a la sartén y cocinar hasta que esté dorada y cocida completamente. Escurrir el exceso de grasa si es necesario.'),
        (24, '4', 'Añadir el tomate triturado, la salsa de tomate, el azúcar, el orégano, la albahaca, el tomillo, la pimienta negra y la sal. Cocinar a fuego medio-bajo durante unos 15-20 minutos, revolviendo de vez en cuando. Luego, retirar del fuego y reservar.'),
        (24, '5', 'En un tazón aparte, mezclar el queso ricotta, la mitad del queso mozzarella rallado, la mitad del queso parmesano rallado, el huevo, las hojas de albahaca fresca picada, sal y pimienta al gusto. Reservar.'),
        (24, '6', 'En una olla grande, hervir agua con sal y cocinar las láminas de lasaña según las instrucciones del paquete hasta que estén al dente. Escurrir y enjuagar con agua fría para detener la cocción.'),
        (24, '7', 'Ensamblar la lasaña: En una fuente para horno rectangular, colocar una capa delgada de la salsa de carne en el fondo. Luego, colocar una capa de láminas de lasaña cocidas encima. Luego, agregar una capa de la mezcla de queso ricotta reservada. Repetir estos pasos alternando capas de salsa de carne, láminas de lasaña y mezcla de queso ricotta, hasta que se agoten los ingredientes terminando con una capa de salsa de carne y queso.'),
        (24, '8', 'Hornea la lasagna en el horno precalentado por unos 30-35 minutos, o hasta que esté caliente y burbujeante en los bordes.'),
        (24, '9', 'Retira la lasagna del horno y deja reposar por unos minutos antes de cortarla y servirla. Decora con hojas de albahaca fresca si lo deseas.'),

        (25, '1', 'Precalienta el horno a 180°C (350°F).'),
        (25, '2', 'Coloca las pechugas de pollo entre dos hojas de papel plástico y golpéalas con un mazo de carne para aplanarlas hasta que tengan un grosor uniforme de aproximadamente 1 cm. Sazona las pechugas de pollo con sal y pimienta al gusto.'),
        (25, '3', 'En tres platos separados, coloca la harina, los huevos batidos y una mezcla de pan rallado y queso parmesano rallado.'),
        (25, '4', 'Pasa cada pechuga de pollo primero por la harina, luego por los huevos batidos y finalmente por la mezcla de pan rallado y queso parmesano, presionando ligeramente para que se adhiera bien la cobertura.'),
        (25, '5', 'Calienta suficiente aceite de oliva en una sartén grande a fuego medio-alto. Agrega las pechugas de pollo empanizadas y fríe por unos 3-4 minutos por lado, o hasta que estén doradas y cocidas por completo. Transfiere las pechugas de pollo a un plato cubierto con papel absorbente para eliminar el exceso de aceite.'),
        (25, '6', 'En una fuente para horno, coloca una capa delgada de salsa de tomate para pasta en el fondo. Luego, coloca las pechugas de pollo fritas encima.'),
        (25, '7', 'Cubre las pechugas de pollo con una capa generosa de salsa de tomate para pasta y luego espolvorea el queso mozzarella rallado por encima.'),
        (25, '8', 'Hornea el pollo a la parmesana en el horno precalentado por unos 15-20 minutos, o hasta que el queso esté derretido y burbujeante.'),
        (25, '9', 'Retira del horno y deja reposar por unos minutos antes de servir. Decora con hojas de albahaca fresca si lo deseas.'),

        (26, '1', 'En un tazón grande, bate las yemas de huevo con la mitad del azúcar hasta obtener una mezcla espumosa y de color claro.'),
        (26, '2', 'Agrega el queso mascarpone a la mezcla de yemas de huevo y azúcar, y bate hasta que esté bien incorporado y suave.'),
        (26, '3', 'En otro tazón limpio y seco, bate las claras de huevo a punto de nieve. Agrega el azúcar restante poco a poco, batiendo hasta obtener picos firmes.'),
        (26, '4', 'Incorpora las claras de huevo batidas a la mezcla de mascarpone y yemas en forma suave y envolvente, para que la mezcla no pierda aire.'),
        (26, '5', 'Mezcla el café espresso con el licor de café (si lo estás utilizando) en un plato hondo.'),
        (26, '6', 'Remoja las galletas de savoiardi o soletillas brevemente en la mezcla de café y licor, asegurándote de que no se empapen demasiado para que no se deshagan.'),
        (26, '7', 'Coloca una capa de las galletas remojadas en el fondo de un molde para servir.'),
        (26, '8', 'Cubre las galletas con una capa de la mezcla de mascarpone y repite las capas alternando las galletas y la mezcla de mascarpone, terminando con una capa de mascarpone en la parte superior.'),
        (26, '9', 'Espolvorea generosamente con cacao en polvo sobre la capa final de mascarpone.'),
        (26, '10', 'Refrigera el tiramisú durante al menos 4 horas, o preferiblemente durante la noche, para que los sabores se mezclen y la textura se asiente.'),
        (26, '11', 'Justo antes de servir, decora con chocolate rallado (si lo estás utilizando).'),
        (26, '12', '¡Disfruta de tu delicioso tiramisú casero!'),

        (27, '1', 'En una sartén grande, calienta 2 cucharadas de aceite vegetal a fuego alto. Agrega el lomo de res y saltea durante 3-4 minutos o hasta que esté dorado. Retira el lomo de la sartén y reserva.'),
        (27, '2', 'Agrega las 2 cucharadas restantes de aceite vegetal a la sartén y agrega la cebolla, los tomates, los pimientos y el ajo. Cocina durante 3-4 minutos o hasta que las verduras estén tiernas pero aún crujientes.'),
        (27, '3', 'Agrega la salsa de soja, el vinagre blanco, el aji amarillo molido y sal y pimienta al gusto. Cocina durante 2-3 minutos más.'),
        (27, '4', 'Agrega el lomo de res de vuelta a la sartén y mezcla todo junto. Cocina durante 1-2 minutos más para que los sabores se integren.'),
        (27, '5', 'Sirve el Lomo Saltado caliente, decorado con cilantro fresco picado y acompaña con papas fritas y arroz blanco cocido.'),

        (28, '1', 'En un tazón, mezcla el jugo de limón, el jugo de naranja, el ajo picado, el comino, la paprika, la pimienta negra molida y la sal para marinar el pescado.'),
        (28, '2', 'Coloca los filetes de pescado en la marinada y deja reposar durante al menos 30 minutos en el refrigerador.'),
        (28, '3', 'Mientras tanto, prepara la salsa de yogur. En un tazón pequeño, mezcla el yogur, la mayonesa, el cilantro picado, el jugo de limón, la salsa picante (si lo deseas), la sal y la pimienta. Reserva en el refrigerador.'),
        (28, '4', 'Calienta una parrilla o sartén a fuego medio-alto. Retira los filetes de pescado de la marinada y cocínalos en la parrilla o sartén caliente durante aproximadamente 3-4 minutos por cada lado, o hasta que estén cocidos y se desmenucen fácilmente con un tenedor.'),
        (28, '5', 'Retira los filetes de pescado cocidos de la parrilla o sartén y déjalos reposar durante unos minutos antes de desmenuzarlos en trozos grandes.'),
        (28, '6', 'Calienta las tortillas de maíz en una sartén o en el horno hasta que estén calientes y flexibles.'),
        (28, '7', 'Para armar los tacos, coloca una porción de pescado desmenuzado en el centro de cada tortilla. Agrega repollo rallado o col picada finamente encima del pescado.'),
        (28, '8', 'Espolvorea con un poco de salsa de yogur por encima y decora con rodajas de limón.'),
        (28, '9', 'Sirve los tacos de pescado con más salsa de yogur y disfruta de esta deliciosa y fresca comida.'),

        (29, '1', 'En una cazuela grande, calienta el aceite de oliva y 2 cucharadas de mantequilla a fuego medio. Añade la cebolla y el ajo, y cocina hasta que estén tiernos y fragantes, aproximadamente 3-4 minutos.'),
        (29, '2', 'Agrega los champiñones a la cazuela y cocine hasta que se ablanden y se doren ligeramente, alrededor de 5-6 minutos. Reserva algunas rodajas de champiñones para decorar al final.'),
        (29, '3', 'Añade el arroz Arborio a la cazuela y cocine durante 2-3 minutos, revolviendo constantemente, hasta que el arroz esté ligeramente dorado.'),
        (29, '4', 'Agrega el vino blanco al arroz y cocina hasta que se haya absorbido por completo.'),
        (29, '5', 'Comienza a añadir el caldo caliente, una taza a la vez, revolviendo constantemente y esperando a que se absorba antes de añadir más caldo. Continúa este proceso hasta que el arroz esté cocido al dente, lo que debería tomar aproximadamente 20 minutos.'),
        (29, '6', 'Retira la cazuela del fuego y agrega el queso parmesano rallado y las 2 cucharadas restantes de mantequilla. Revuelve bien para que todo quede bien mezclado.'),
        (29, '7', 'Sazona con sal y pimienta al gusto.'),
        (29, '8', 'Sirve el risotto de champiñones caliente, decorado con las rodajas de champiñones reservadas y perejil fresco picado si lo deseas.'),

        (30, '1', 'Prepara la masa de pizza: En un tazón grande, mezcla la harina, la levadura seca, la sal y el azúcar. Agrega el agua tibia y el aceite de oliva, y mezcla bien hasta que se forme una masa suave y elástica.'),
        (30, '2', 'Amasa la masa en una superficie enharinada durante unos 5-7 minutos, o hasta que esté suave y elástica. Forma una bola con la masa y colócala en un tazón engrasado. Cubre con un paño húmedo y deja reposar durante aproximadamente 1 hora, o hasta que la masa haya duplicado su tamaño.'),
        (30, '3', 'Precalienta el horno a 230°C (450°F) y coloca una piedra de pizza o una bandeja para hornear en el horno para que se caliente.'),
        (30, '4', 'Una vez que la masa haya reposado y haya duplicado su tamaño, colócala en una superficie enharinada y amásala brevemente para quitar el exceso de aire. Luego, estírala con un rodillo para formar una base redonda o rectangular, según tus preferencias.'),
        (30, '5', 'Transfiere la masa estirada a la piedra de pizza o a la bandeja para hornear caliente y añade la salsa de tomate sobre la superficie de la masa, dejando un borde de 1 cm sin cubrir. Luego, esparce el queso mozzarella rallado sobre la salsa.'),
        (30, '6', 'Agrega el jamón de pierna cortado en cubos, las rodajas de piña y las rodajas finas de cebolla roja sobre la pizza.'),
        (30, '7', 'Hornea la pizza en el horno precalentado durante unos 12-15 minutos, o hasta que los bordes estén dorados y el queso esté derretido y burbujeante.'),
        (30, '8', 'Retira la pizza del horno y deja que se enfríe un poco antes de cortarla en porciones. Si lo deseas, puedes decorar la pizza con hojas de albahaca fresca antes de servirla.');