INSERT INTO recetas (nombre, duracion, tiempo_comida, tiempo_receta, porciones, imagen, calificacion, Usuarios_correo)
VALUES ('Pancakes de Arándanos', '30 minutos', 'desayuno', 'principal', '4', null, 5, 'juanperez1234@gmail.com'),   
       ('Ensalada César', '15 minutos', 'comida', 'entrada', '2', null, 4, 'juanperez1234@gmail.com'),              
       ('Sopa de Tomate', '40 minutos', 'comida', 'entrada', '6', null, 3, 'juanperez1234@gmail.com'),              
       ('Smoothie de Frutas', '5 minutos', 'merienda', 'bebida', '1', null, 5, 'juanperez1234@gmail.com'),          
       ('Lomo de Cerdo al Horno', '120 minutos', 'cena', 'principal', '6', null, 4, 'juanperez1234@gmail.com'),  
       ('Pastel de Chocolate', '90 minutos', 'postre', 'postre', '8', null, 4, 'juanperez1234@gmail.com'),         
       ('Tacos de Carnitas', '2 horas', 'comida', 'principal', '4', null, 5, 'juanperez1234@gmail.com'),           
       ('Ensalada de Quinoa', '20 minutos', 'almuerzo', 'ensalada', '3', null, 4, 'juanperez1234@gmail.com'),      
       ('Pasta Alfredo con Pollo', '45 minutos', 'comida', 'principal', '6', null, 3, 'juanperez1234@gmail.com'),  
       ('Smoothie Verde Detox', '10 minutos', 'desayuno', 'bebida', '1', null, 5, 'juanperez1234@gmail.com'),  
       ('Pizza Margherita', '45 minutos', 'cena', 'principal', '8', null, 4, 'juanperez1234@gmail.com'),           
       ('Tarta de Manzana', '1 hora 30 minutos', 'postre', 'postre', '6', null, 4, 'juanperez1234@gmail.com'),     
       ('Ceviche de Camarón', '20 minutos', 'comida', 'entrada', '4', null, 0, 'juanperez1234@gmail.com'),         
       ('Hamburguesa de Pollo', '30 minutos', 'comida', 'principal', '4', null, 3, 'juanperez1234@gmail.com'),     
       ('Sopa de Lentejas', '50 minutos', 'comida', 'entrada', '6', null, 4, 'juanperez1234@gmail.com'),        
       ('Enchiladas Verdes', '1 hora', 'cena', 'principal', '4', null, 4, 'mariarod9876@gmail.com'),               
       ('Pastel de Zanahoria', '1 hora 15 minutos', 'postre', 'postre', '10', null, 3, 'mariarod9876@gmail.com'),  
       ('Ensalada de Atún', '15 minutos', 'almuerzo', 'ensalada', '2', null, 4, 'mariarod9876@gmail.com'),         
       ('Pasta Carbonara', '25 minutos', 'comida', 'principal', '4', null, 2, 'mariarod9876@gmail.com'),        
       ('Smoothie de Mango', '5 minutos', 'merienda', 'bebida', '1', null, 5, 'mariarod9876@gmail.com'),     
       ('Sushi de Salmón', '30 minutos', 'cena', 'principal', '4', null, 4, 'mariarod9876@gmail.com'),
       ('Ceviche de Pulpo', '20 minutos', 'comida', 'entrada', '4', null, 5, 'pedrogomez12@gmail.com'),
       ('Parrillada Argentina', '1 hora 30 minutos', 'cena', 'principal', '6', null, 4, 'pedrogomez12@gmail.com'),
       ('Lasagna de Carne', '1 hora', 'comida', 'principal', '8', null, 3, 'pedrogomez12@gmail.com'),
       ('Pollo a la Parmesana', '40 minutos', 'cena', 'principal', '4', null, 4, 'pedrogomez12@gmail.com'),
       ('Tiramisú', '30 minutos', 'postre', 'postre', '6', null, 4, 'pedrogomez12@gmail.com'),
       ('Lomo Saltado', '40 minutos', 'cena', 'principal', '4', null, 5, 'pedrogomez12@gmail.com'),
       ('Tacos de Pescado', '25 minutos', 'cena', 'principal', '4', null, 4, 'pedrogomez12@gmail.com'),
       ('Risotto de Champiñones', '40 minutos', 'cena', 'principal', '4', null, 4, 'anamartinp@gmail.com'),
       ('Pizza Hawaiana', '45 minutos', 'cena', 'principal', '8', null, 4, 'anamartinp@gmail.com');


