-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 14:36:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recetasDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recetasDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recetasDB` DEFAULT CHARACTER SET utf8 ;
USE `recetasDB` ;

-- -----------------------------------------------------
-- Table `recetasDB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasDB`.`Usuarios` (
  `correo` VARCHAR(255) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetasDB`.`Recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasDB`.`Recetas` (
  `idRecetas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `tiempo_comida` VARCHAR(45) NOT NULL,
  `tiempo_receta` VARCHAR(45) NOT NULL,
  `porciones` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `Usuarios_correo` VARCHAR(255) NOT NULL,
  `caificacion` INT NOT NULL,
  PRIMARY KEY (`idRecetas`, `Usuarios_correo`),
  INDEX `fk_Recetas_Usuarios1_idx` (`Usuarios_correo` ASC),
  CONSTRAINT `fk_Recetas_Usuarios1`
    FOREIGN KEY (`Usuarios_correo`)
    REFERENCES `recetasDB`.`Usuarios` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetasDB`.`Ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasDB`.`Ingredientes` (
  `idIngredientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `unidad_medida` VARCHAR(45) NOT NULL,
  `Usuarios_correo` VARCHAR(255),
  PRIMARY KEY (`idIngredientes`, `Usuarios_correo`),
  INDEX `fk_Ingredientes_Usuarios1_idx` (`Usuarios_correo` ASC),
  CONSTRAINT `fk_Ingredientes_Usuarios1`
    FOREIGN KEY (`Usuarios_correo`)
    REFERENCES `recetasDB`.`Usuarios` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetasDB`.`Pasos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasDB`.`Pasos` (
  `idPasos` INT NOT NULL,
  `paso` TEXT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `Recetas_idRecetas` INT NOT NULL,
  PRIMARY KEY (`idPasos`),
  INDEX `fk_Pasos_Recetas1_idx` (`Recetas_idRecetas` ASC),
  CONSTRAINT `fk_Pasos_Recetas1`
    FOREIGN KEY (`Recetas_idRecetas`)
    REFERENCES `recetasDB`.`Recetas` (`idRecetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetasDB`.`Recetas_has_Ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasDB`.`Recetas_has_Ingredientes` (
  `Recetas_idRecetas` INT NOT NULL,
  `Ingredientes_idIngredientes` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`Recetas_idRecetas`, `Ingredientes_idIngredientes`),
  INDEX `fk_Recetas_has_Ingredientes_Ingredientes1_idx` (`Ingredientes_idIngredientes` ASC),
  INDEX `fk_Recetas_has_Ingredientes_Recetas1_idx` (`Recetas_idRecetas` ASC),
  CONSTRAINT `fk_Recetas_has_Ingredientes_Recetas1`
    FOREIGN KEY (`Recetas_idRecetas`)
    REFERENCES `recetasDB`.`Recetas` (`idRecetas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recetas_has_Ingredientes_Ingredientes1`
    FOREIGN KEY (`Ingredientes_idIngredientes`)
    REFERENCES `recetasDB`.`Ingredientes` (`idIngredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
